name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build gcc11
      run: |
        docker build . --file .github/workflows/Dockerfile --tag gcc11:$(date +%s) --build-arg VARIANT=gcc11
