name: BuildServer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [12, 14, 16]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Code format check
      if: matrix.os == 'ubuntu-latest'
      uses: jidicula/clang-format-action@v4.6.2

    - name: Install conan
      uses: turtlebrowser/get-conan@main

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DSTATIC_ANALYZERS=1 -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build  --target install

    - name: CTest
      run: |
        cd ${{github.workspace}}/build
        ctest .

    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Jest
      run: |
        cd ${{github.workspace}}/src/libhello/bindings/node/test
        npm install
        npm test

    - name: Run native
      run: |
        ${{github.workspace}}/target/hello

    - name: Run node
      run: |
        cd ${{github.workspace}}/src/node_hello
        npm install
        node index.js
